from use_case.common.command import Command


class ReportCommand(Command): ...
class QuantityBooksAndUsersCommand(Command): ...
class RatingAuthorCommand(Command): ...
class RatingGenreCommand(Command): ...
class UsersStatisticCommand(Command): ...
